#!/usr/bin/env python3
"""
Generate a 4-player plastic map: lakes with closed coasts, rock-outlined plateaus with ramps,
balanced gold / coal / forests, 4 start points and 6 races (human + orc, red/blue/yellow).

Usage:
    python3 generate_map.py --seed 7 -o maps/four_lakes.map [--name "Four Lakes"] [--preview p.png]

Checks: python3 map_check.py <map>  and  python3 validate_map.py <map>
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

from map_check import HANDMADE, check_adjacency, learn_adjacency, repo_root, walkable_grid
from mapgen_layout import FRAG, layout_grid, make_layout
from mapgen_resources import place_resources
from mapgen_tiles import fragment_ids, ug_name

RACES = ["human-red", "human-blue", "human-yellow", "orc-red", "orc-blue", "orc-yellow"]
START_MATERIALS = "1500 1000 1000"
# start village relative to the start point (town hall is 7x7, anchored at the start point)
START_UNITS = [("peasant", 1, 8, 0), ("peasant", 3, 8, 0), ("peasant", 5, 8, 0), ("peasant", 7, 8, 0),
               ("footman", 8, 1, 2), ("footman", 8, 4, 2)]


def _players(starts) -> str:
    lines = ["<Players>", "  max_count 4", "  ", "  <Start Points>", f"    count {len(starts)}", "    "]
    lines += [f"    start_point_{i} {x} {y}" for i, (x, y) in enumerate(starts)]
    lines += ["  </Start Points>", "  ", "  <Races>", f"    count {len(RACES)}", "    "]
    for i, race in enumerate(RACES):
        lines += [f"    <Race {i}>", f'      name "{race}"', "      ", "      <Sets>", "        count 1", "        ",
                  "        <Set 0>", f"          init_materials_amount {START_MATERIALS}", "          ",
                  "          <Units>", f"            count {len(START_UNITS)}"]
        for j, (uid, x, y, d) in enumerate(START_UNITS):
            tail = "    unit id, x position, y position, z position, direction, life" if j == 0 else ""
            lines.append(f'            unit_{j} "{uid}" {x} {y} 1 {d} 100{tail}')
        lines += ["          </Units>", "          ", "          <Buildings>", "            count 1",
                  '            building_0 "townhall" 0 0 100    building id, x position, y position, life',
                  "          </Buildings>", "        </Set 0>", "      </Sets>", f"    </Race {i}>", "    "]
    return "\n".join(lines)


def _scheme_race(sources) -> str:
    lines = ["    <SchemeRace>", '      name "plastic"', "      ", "      <Sources>", f"        count {len(sources)}",
             "        "]
    for i, (sid, x, y, life, amt) in enumerate(sources):
        tail = " source id, x position, y position, life, material balance" if i == 0 else ""
        lines.append(f'        source_{i} "{sid}" {x} {y} {life} {amt}{tail}')
    lines += ["        ", "      </Sources>", "      ", "      <Units>", "        count 0", "      </Units>", "      ",
              "      <Buildings>", "        count 0", "      </Buildings>", "    </SchemeRace>", "    ",
              "  </Races>", "  ", "</Players>"]
    return "\n".join(lines)


def _segment(seg: int, ids: np.ndarray) -> str:
    h, w = ids.shape
    lines = [f"<Segment {seg}>", "  <Fragments>", f"    count {h * w}"]
    k = 0
    for cx in range(w):
        for cy in range(h):
            lines.append(f"    fragment_{k} {int(ids[cy, cx])} {cx * FRAG} {cy * FRAG}")
            k += 1
    lines += ["  </Fragments>", "  ", "  <Layers>", "    count 0", "  </Layers>", "  ", "  <Objects>",
              "    count 0", "  </Objects>", f"</Segment {seg}>"]
    return "\n".join(lines)


def generate(seed: int, out: Path, name: str | None = None, cells: int = 32) -> Path:
    root = repo_root()
    sch = root / "schemes" / "plastic.sch"
    allowed = learn_adjacency([root / "maps" / n for n in HANDMADE], sch)
    # rare shapes (e.g. two diagonally offset notches) have no seamless fragments: try the next
    # layout derived from the seed until the fragment check passes (still deterministic)
    for attempt in range(20):
        lay = make_layout(seed * 97 + attempt, cells)
        grid = layout_grid(lay)
        if not check_adjacency(grid, allowed, sch):
            break
    else:
        raise RuntimeError(f"no seamless layout for seed {seed}")
    walk = walkable_grid(grid, sch, [])
    sources = place_resources(lay, walk, np.random.default_rng(seed))

    ids1, ids0 = fragment_ids(sch, 1), fragment_ids(sch, 0)
    g1 = np.vectorize(lambda n: ids1[n])(grid)
    g0 = np.vectorize(lambda n: ids0[ug_name(n)])(grid)
    g2 = np.zeros_like(g1)

    size = cells * FRAG
    title = name or f"Generated {seed}"
    head = "\n".join(["#", "#  " + "=" * (len(title) + 2), f"#   {title}", "#  " + "=" * (len(title) + 2),
                      f"#  generated by generate_map.py --seed {seed}", "#", "",
                      f'name "{title}"', 'author "generate_map.py"', f"width {size}", f"height {size}",
                      'scheme "plastic"', "", ""])
    # <SchemeRace> lives inside <Races>; _scheme_race also closes </Races> and </Players>
    players = _players(lay.starts) + "\n" + _scheme_race(sources)
    body = "\n\n\n".join([players, _segment(0, g0), _segment(1, g1), _segment(2, g2)])
    Path(out).write_text(head + body + "\n", encoding="latin-1")
    return Path(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("-o", "--out", type=Path, required=True)
    ap.add_argument("--name", default=None)
    ap.add_argument("--preview", type=Path, default=None)
    a = ap.parse_args()
    generate(a.seed, a.out, a.name)
    print(f"wrote {a.out}")
    if a.preview:
        from render_map import render
        render(a.out, a.preview)
        print(f"preview {a.preview}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
